{% set name = "orgparse" %}
{% set version = "0.4.20250520" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orgparse-{{ version }}.tar.gz
  sha256: 6472fd16ddcabb523918505c865263abfa05ac80b593e668a089cda291b1a2de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - orgparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karlicoss/orgparse
  summary: orgparse - Emacs org-mode parser in Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
