{% set name = "orgparse" %}
{% set version = "0.4.20231004" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orgparse-{{ version }}.tar.gz
  sha256: a4e38aeadabf9988b0f67a66acd08279d18220bcbc422a129060c2890bba91a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - orgparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karlicoss/orgparse
  summary: orgparse - Emacs org-mode parser in Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
